{"reklam":"https://github.com/YmirSonmez/Yedi70/blob/main/r.jpg?raw=true","link":"https://t.me/YmirSG","counter":"https://tinyurl.com/ts38m9tk",
  "button_1_name":"Yedi70 Telegram",
  "button_1_link":"https://t.me/+wC0eF2DdiZ81MTNk",
  "button_2_name":"Yedi70 Instagram",
  "button_2_link":"https://www.instagram.com/yedi70kazan/",
  "button_3_name":"Bot Güncellemeleri",
  "button_3_link":"https://t.me/blumfarmbott",
  "button_4_name":"WiKi",
  "button_4_link":"https://ymirsonmez.github.io/Yedi70.github.io/",
  "button_5_name":"TG Desktop",
  "button_5_link":"https://desktop.telegram.org/",
  "bot_active":"1"}
